spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees_and_companies
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "lana"
    password: "2050165454jhX@"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop